s_dim: -1
h_dim: 200
a_dim: -1
max_len: 10
dropout: 0.1
embed_size: -1
residual: True
gumbel: True
temperature: 1e-3
paths: 10
tau_plan_a: 1e-3
tau_plan_t: 1e-3
name: "PEDP"
beta: 0.5
opt: "Adam"
activation: "relu"
lr: 1e-3
class_correction: False
batch_size: 32
epochs: 10